#version: '3.8'
#
#services:
#  web:
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile
#    image: django_web
#    # '/start' is the shell script used to run the service
#    command: /start
#    # this volume is used to map the files and folders on the host to the container
#    # so if we change code on the host, code in the docker container will also be changed
#    volumes:
#      - .:/app
#    ports:
#      - 8010:8000
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - rabbitmq
#      - db
#
#  db:
#    image: postgres:15-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_PASSWORD=1
#
#  redis:
#    image: redis:alpine
#
#  rabbitmq:
#    image: rabbitmq:management
#    container_name: rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    ports:
#      - 5672:5672
#      - 15672:15672
#
#  celery_worker:
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile
#    image: celery_worker
#    command: /start-celeryworker
#    volumes:
#      - .:/app
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - rabbitmq
#      - db
#
#  celery_beat:
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile
#    image: celery_beat
#    command: /start-celerybeat
#    volumes:
#      - .:/app
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - rabbitmq
#      - db
#
#  flower:
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile
#    image: django_celery_example_celery_flower
#    command: /start-flower
#    volumes:
#      - .:/app
#    env_file:
#      - .env
#    ports:
#      - 5557:5555
#    depends_on:
#      - redis
#      - db
#
#volumes:
#  postgres_data: